name
 
on
  push: 
    branches: 
      - main 
  pull_request: 
    branches: 
      - main 
 
jobs: 
  build: 
    name
runs-
     
    steps: 
-
      uses: actions/checkout@v2 
     
-
      uses: actions/setup-node@v1 
      with
        node-version: 13.x 
     
-
      run: npm ci 
     
-
      run: npm run build 
     
-
      run: npm run test 
 
-
      uses: actions/upload-artifact@v2 
      with
        name
        path: ./build 
   
  deploy: 
    name
    needs: build 
runs-
if: github.ref == 
     
    steps: 
-
      uses: actions/download-artifact@v2 
      with
        name
        path: ./build 
 
-
      uses: peaceiris/actions-gh-pages@v3 
      with
        github_token: ${{ secrets.GITHUB_TOKEN }} 
        publish_dir: ./build 
